name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Validate
        run: |
          cd infra
          terraform validate

      - name: Terraform Plan
        run: |
          cd infra
          terraform plan

      - name: Copy Lambda function to Terraform directory
        run: |
          cp app/lambda_function.py infra/lambda_function.py

      - name: Check Terraform State
        run: |
          cd infra
          terraform state list
        continue-on-error: true  # Ignora erros se o recurso não estiver no estado

      - name: Import IAM Role (se necessário)
        run: |
          cd infra
          terraform import aws_iam_role.lambda_exec_role lambda_exec_role
        continue-on-error: true  # Ignora erros se o recurso já estiver importado

      - name: Force Replace IAM Role
        run: |
          cd infra
          terraform taint aws_iam_role.lambda_exec_role

      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve
