name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Validate
        run: |
          cd infra
          terraform validate

      - name: Copy Lambda function to Terraform directory
        run: |
          cp app/lambda_function.py infra/lambda_function.py

      - name: Check if Event Source Mapping Exists
        id: check_mapping
        run: |
          cd infra
          # Verificar se o mapeamento já existe
          EXISTING_MAPPING=$(terraform state list | grep aws_lambda_event_source_mapping.dynamodb_stream_trigger || echo "not found")
          if [ "$EXISTING_MAPPING" != "not found" ]; then
            echo "Event source mapping already exists. Skipping creation."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "No existing event source mapping found. Will create a new one."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Import IAM Role if not in state
        run: |
          cd infra
          terraform state list | grep aws_iam_role.lambda_exec_role || terraform import aws_iam_role.lambda_exec_role lambda_exec_role

      - name: Import Lambda function if not in state
        run: |
          cd infra
          terraform state list | grep aws_lambda_function.lambda-dynamo-replica-stream || terraform import aws_lambda_function.lambda-dynamo-replica-stream lambda-dynamo-replica-stream

      - name: Terraform Plan
        run: |
          cd infra
          terraform plan

      - name: Terraform Apply
        if: env.exists == 'false'  # Só aplica se não existir mapeamento
        run: |
          cd infra
          terraform apply -auto-approve
